---
- name: Make sure that the traefik directory exists
  become: true
  file:
    group: "{{ traefik_group }}"
    owner: "{{ traefik_user }}"
    path: "{{ traefik_dir }}"
    state: directory
    mode: "0744"

- name: Copy traefik config
  template:
    dest: "{{ traefik_dir }}/traefik.toml"
    force: true
    src: templates/traefik.toml.j2

- name: Copy acme.json
  copy:
    dest: "{{ traefik_dir }}/acme.json"
    force: false
    mode: 0600
    src: files/acme.json

- name: Create network (basic)
  docker_network:
    driver: "{{ traefik_network_driver }}"
    name: "{{ traefik_network }}"
  when: not traefik_network_attachable

# Use a command here to create an attachable container, until Ansible
# updates their docker_network module to permit it.
- name: Create network (advanced)
  command: "docker network create --driver {{ traefik_network_driver }} --attachable {{ traefik_network }}"
  args:
    warn: no
  when: traefik_network_attachable

- name: Run traefik proxy (w/ web interface)
  docker_container:
    labels:
      traefik.backend: traefik
      traefik.frontend.rule: "Host: traefik.{{ traefik_docker_domain }}"
      traefik.port: "8080"
      traefik.priority: "1"
    image: traefik:latest
    name: traefik
    networks:
      - name: "{{ traefik_network }}"
    pull: true
    ports:
      - "443:443"
      - "80:80"
    recreate: true
    restart_policy: always
    state: "{{ traefik_state }}"
    volumes: '[ "/var/run/docker.sock:/var/run/docker.sock", "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml", "{{ traefik_dir }}/acme.json:/etc/traefik/acme.json" ] + {{ traefik_volumes }}'
  when: traefik_enable_web

- name: Run traefik proxy (w/o web interface)
  docker_container:
    image: traefik:latest
    name: traefik
    networks:
      - name: "{{ traefik_network }}"
    pull: true
    ports:
      - "443:443"
      - "80:80"
    recreate: true
    restart_policy: always
    state: "{{ traefik_state }}"
    volumes: '[ "/var/run/docker.sock:/var/run/docker.sock", "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml", "{{ traefik_dir }}/acme.json:/etc/traefik/acme.json" ] + {{ traefik_volumes }}'
  when: not traefik_enable_web
